from pydantic import BaseModel, Field

class UploaderData(BaseModel):
    Language: str
    Title: str
    Subtitle: str
    Series: str = ""
    Author_prefix: str = Field("", alias="Author prefix")
    Author_first_name: str = Field("", alias="Author first name")
    Author_last_name: str = Field("", alias="Author last name")
    Contributor_role: str = Field("", alias="Contributor role")
    Contributor_prefix: str = Field("", alias="Contributor prefix")
    Contributor_first_name: str = Field("", alias="Contributor first name")
    Contributor_last_name: str = Field("", alias="Contributor last name")
    Description: str
    Public_Domain: str = Field("No", alias="Public Domain")
    Minimum_age: str = Field("3", alias="Minimum age")
    Maximum_age: str = Field("100", alias="Maximum age")
    Primary_Marketplace: str = Field("Amazon.com", alias="Primary Marketplace")
    Category_1: str = Field("", alias="Category 1")
    Category_2: str = Field("", alias="Category 2")
    Category_3: str = Field("", alias="Category 3")
    Keywords_1: str = Field("", alias="Keywords 1")
    Keywords_2: str = Field("", alias="Keywords 2")
    Keywords_3: str = Field("", alias="Keywords 3")
    Keywords_4: str = Field("", alias="Keywords 4")
    Keywords_5: str = Field("", alias="Keywords 5")
    Keywords_6: str = Field("", alias="Keywords 6")
    Keywords_7: str = Field("", alias="Keywords 7")
    Low_Content_Book: str = Field("No", alias="Low-Content Book")
    Large_print: str = Field("No", alias="Large print")
    ISBN: str = ""
    Imprint: str = ""
    Interior_paper_type: str = Field("Black and white interior with white paper", alias="Interior & paper type")
    Width_in: str = Field("8.5", alias="Width (in)")
    Height_in: str = Field("11", alias="Height (in)")
    Bleed_Settings: str = Field("Bleed", alias="Bleed Settings")
    Paperback_cover_finish: str = Field("Matte", alias="Paperback cover finish")
    Cover_include_barcode: str = Field("Yes", alias="Cover include barcode")
    AI_Generated: str = Field("Yes", alias="AI-Generated")
    AI_Texts: str = Field("No", alias="AI-Texts")
    AI_Texts_Tool: str = Field("", alias="AI-Texts-Tool")
    AI_Images: str = Field("Yes", alias="AI-Images")
    AI_Images_Tools: str = Field("", alias="AI-Images-Tools")
    AI_Translations: str = Field("Yes", alias="AI-Translations")
    AI_Translations_Tool: str = Field("", alias="AI-Translations-Tool")
    Base_all_prices_on_primary: str = Field("Yes", alias="Base all prices on Primary Marketplace price")
    Expanded_Distribution: str = Field("Yes", alias="Expanded Distribution")
    Amazon_com: str = Field("4.99", alias="Amazon.com")
    Amazon_co_uk: str = Field("4.99", alias="Amazon.co.uk")
    Amazon_de: str = Field("4.99", alias="Amazon.de")
    Amazon_fr: str = Field("4.99", alias="Amazon.fr")
    Amazon_es: str = Field("4.99", alias="Amazon.es")
    Amazon_it: str = Field("4.99", alias="Amazon.it")
    Amazon_ca: str = Field("4.99", alias="Amazon.ca")
    Amazon_com_au: str = Field("4.99", alias="Amazon.com.au")
    Amazon_nl: str = Field("4.99", alias="Amazon.nl")
    Amazon_pl: str = Field("4.99", alias="Amazon.pl")
    Amazon_se: str = Field("4.99", alias="Amazon.se")
